{% set version = "2.9.5" %}

package:
  name: libxml2
  version: {{ version }}

source:
  fn: libxml2-{{ version }}.tar.gz
  url: https://git.gnome.org/browse/libxml2/snapshot/libxml2-{{ version }}.tar.gz
  sha256: 7aaf3e1f03317231864f833eea25a30721cc7b434884e089cc3a021b6d58f60c

build:
  number: 0
  skip: true  # [win and py>35]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python  # [win]
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - pkg-config  # [not win]
    - icu 58.*  # [not win]
    - libiconv
    - zlib 1.2.*
    - xz 5.2.*  # [not win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - icu 58.*  # [not win]
    - libiconv
    - zlib 1.2.*
    - xz 5.2.*  # [not win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]

test:
  files:
    - test.xml
  commands:
    - xmllint test.xml
    - conda inspect linkages -p $PREFIX libxml2  # [not win]
    - conda inspect objects -p $PREFIX libxml2  # [osx]

about:
  home: http://xmlsoft.org/
  license: MIT
  license_file: Copyright
  summary: 'The XML C parser and toolkit of Gnome.'

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
    - gillins
    - jschueller
