# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Eru8bqyWL46VOC0+cBQRJCljUbc3ULnJPlZ/SBME6k5k6YvmqPknmGwnQ1cViLiAewaDk3P+W0QhfIvEf++ULDOhraV87wwNM9wdgDlsFd21MHYbVGFORpeF7Lwoj7HJO2qTxd5Tvt+cniRBZgDI5ScvjFY/uwcjQ9cR2CR3El64bo7NtXP6mIxp8tIqVcD7mchArbK3kMiYNV72BR3HlfEccPJfXkE890HNoVgo3ytY+bOhB3QRkCLwrHQnCfjG9k012V2oRj3uVSjTCWfHMBcYe8kTFrzzScjgIMUlE+m5uBjW0RQLJ+ruWsJtGv8q+Kzc7v71a04NnrIBp8li+bG+11tM4MLtd1g28/tScD7m8mxfeZ22umSn47uKDTQYSKvg5VDymPEx/AmlGyANuathOAiDe2fYgleGDO1RhPl36O9MxWMENROtscgRtQZ3w7tdR3kg+0qXgz29oIHaBosFMptxe9BXHxrAUtddU5yKwIa1OomYlyjM4nL+4++oPjZXqaxdWv8xO6KM8lu6FK8ODtII96/Xa+/nC+SfLFQKdPfDJRGq3N2Al2pWhnrLOXHfTiCEC46sQ685BFtq0cYJlikwzlvTag14nIjfv/ha/QknsEMf3FeYqS4A5aMLdnYBVG2QgGX+3CIszI4cFX8sVjIBvd3Qrj/iNazO+2w="


before install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
