travis:
  secure:
    BINSTAR_TOKEN: kTBIuTyBldBX0/kVv/JlYEtGHLzDgVk0P0urS3MieFOzgT8YyNwMeHvSBV2h5JY8x0CLuv6wmziS2whAZ86n69X5RBZMeL4ruaIisd5m0oONs2vPnA6t8gmiOQqLU/6yZLAdPJjlTZFXTAqAZGo17CiI9bWDmi/zWGDL8E5MViGBnTbVEUpZHgB9r/XVTBh3e2f8M8TpHarJELk2MPbGU6Sq9Tzvec3MTJFsciZbgWPeSVwRTEfrP+/nTZf7MXY/gyDJPuAu39c1wWdEHEyzQp1NlL9SECjIbRGVqi5lqdbVPNmqOd5XQIE9MbwZ6w/Pnzk2Ch/I+ruH/pSamIuTKkz7O21vevI9iOHKXYoJjJUkEexx9nnanWmurtfbDXnXi3gP81QtvHoLDkFx5qLpLvp97s9CMQK8YVdDqFbwXL5bqli9XH5fMmtdz+FvfOotxT0tlH4dIeKck2kzrw1o2g+0pdvvKuvKbK6jRRApyaSg9pvLSOPggdl6xPU8/QZqdYx81rV5MnAPf7IEB76NfjmHoVbyXx0wuiZEq5tbkdBicVIlRqRlMJ/9yfhex/AvDgVahkY8ODHMJrwNHHBEeZDEOMYhFfxkN6ZXfIFLi+8TlhGH4CLKA588seqI1vAvqDHHK0vzMLW6S+AnS/plo+gvDcqurPoeQW2brZ5clT8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
