travis:
  secure:
    BINSTAR_TOKEN: Eru8bqyWL46VOC0+cBQRJCljUbc3ULnJPlZ/SBME6k5k6YvmqPknmGwnQ1cViLiAewaDk3P+W0QhfIvEf++ULDOhraV87wwNM9wdgDlsFd21MHYbVGFORpeF7Lwoj7HJO2qTxd5Tvt+cniRBZgDI5ScvjFY/uwcjQ9cR2CR3El64bo7NtXP6mIxp8tIqVcD7mchArbK3kMiYNV72BR3HlfEccPJfXkE890HNoVgo3ytY+bOhB3QRkCLwrHQnCfjG9k012V2oRj3uVSjTCWfHMBcYe8kTFrzzScjgIMUlE+m5uBjW0RQLJ+ruWsJtGv8q+Kzc7v71a04NnrIBp8li+bG+11tM4MLtd1g28/tScD7m8mxfeZ22umSn47uKDTQYSKvg5VDymPEx/AmlGyANuathOAiDe2fYgleGDO1RhPl36O9MxWMENROtscgRtQZ3w7tdR3kg+0qXgz29oIHaBosFMptxe9BXHxrAUtddU5yKwIa1OomYlyjM4nL+4++oPjZXqaxdWv8xO6KM8lu6FK8ODtII96/Xa+/nC+SfLFQKdPfDJRGq3N2Al2pWhnrLOXHfTiCEC46sQ685BFtq0cYJlikwzlvTag14nIjfv/ha/QknsEMf3FeYqS4A5aMLdnYBVG2QgGX+3CIszI4cFX8sVjIBvd3Qrj/iNazO+2w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
