travis:
  secure:
    BINSTAR_TOKEN: UgsXrh2NZvGGCUWupufbUfr/h7JbTeq2pCY7P66QL3+/zbl503oxdsIdfLSn/xBBdfYJzeF3/WL2eyUE9DMOB5u2dnakiAhL4fLKnF1bxA4aLME+2ICJcUZ3xr88pokzDQ4Nxdx/DctEBae2xDAl61OnlwdDm3jXQsLdDV17j5J7dblen2/jrcJ+ZFNu2V0HR0cquPx14JTmNGrYnMaYbFpfqp3Hc+So862pel49gL77yea8AgapJK3a3kT11CgdJhT7d2BzO/bFy81K5Qm4k3Zp5sfZmCkrZZO4StmBKZOIeuF9OWU3G6NO5Uqq5XgK7zOByKAp0nb5EouRvy+JS2iGAAnO2En9QbpWMd1JaeJ56yz+Un91+v96f+6zAS6SiHfRQ+B2i5f2VBdRdU7SL1tp4hFlg6Ge9wNYMXNIQehEbgSuYsTeXtPz+wGzMtOKPsbCymnVGk5dnV+G/CbDj3ed3MsMJYucdpXsXijQ86PzWpHGqsnpKOBqGi/bTy0vtfyA3yrrL/aDBca8M9xHS0oEfqkizF2oqsiJGWnDfMCe+sqm0nu58fGSV9qroUrpl2bmYE8qBd7s8bxyP7ASOSY8sNU4CbRfaqfRhDyaRK4HlbU1c3C51RUc6FVpE5rkbCBiSpl+kMxuXS7svc2UOI05RyOPi01Ojlvd4blXb3k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
